#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2023 S. G. Gottlieb <info.simon@gottliebtfreitag.de>
# SPDX-License-Identifier: CC0-1.0

ROOT_DIR="$(dirname "$(dirname "$(dirname "$(readlink -f "$0")")")")"
${ROOT_DIR}/usr/bin/slix-ld "${0}" /usr/bin/g++ --sysroot "${ROOT_DIR}" "$@"
