#!/usr/bin/env bash

ROOT_DIR="$(dirname "$(dirname "$(dirname "$(dirname "$(dirname "$(dirname "$(readlink -f "$0")")")")")")")"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+"${LD_LIBRARY_PATH}:"}${ROOT_DIR}/usr/lib"
${ROOT_DIR}/usr/lib/ld-linux-x86-64.so.2 --argv0 cc1plus ${ROOT_DIR}/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/.slix-cc1plus "$@"
