#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2023 S. G. Gottlieb <info.simon@gottliebtfreitag.de>
# SPDX-License-Identifier: CC0-1.0

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
exec ${SCRIPT_DIR}/../lib/firefox/firefox "$@"
